name: Deploy

on:
  push:
    branches:
      - auth/be

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH and deploy
        env:
          EC2_KEY: ${{ secrets.EC2_KEY }}
        run: |
          echo "$EC2_KEY" > keyfile
          chmod 600 keyfile
          mkdir -p ~/.ssh
          ssh-keyscan -H ec2-13-60-216-82.eu-north-1.compute.amazonaws.com >> ~/.ssh/known_hosts
          ssh -i keyfile ec2-user@ec2-13-60-216-82.eu-north-1.compute.amazonaws.com "
            git pull origin auth/be
            cd UserAuth
            pm2 kill
            pm2 start index.js
          "
