name: Deploy

on:
  push:
    branches:
      - auth/be

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key and deploy
        env:
          EC2_KEY: ${{ secrets.EC2_KEY }}
        run: |
          # Save EC2 Key to file and set proper permissions
          echo "$EC2_KEY" > keyfile
          chmod 600 keyfile

          # Ensure the .ssh directory exists
          mkdir -p ~/.ssh

          # Add the EC2 instance to the known hosts to prevent SSH authenticity prompt
          ssh-keyscan -H ec2-13-60-216-82.eu-north-1.compute.amazonaws.com >> ~/.ssh/known_hosts

          # Deploy code and manage the app on EC2
          ssh -i keyfile ec2-user@ec2-13-60-216-82.eu-north-1.compute.amazonaws.com << 'EOF'
            # Ensure you're in the correct project directory
            cd ~/UserAuth

            # Pull latest changes
            git pull origin auth/be

            # Restart the application using pm2
            pm2 restart server.js || pm2 start server.js --name "user-auth-app"
          EOF

          # Clean up SSH keyfile after use
          rm -f keyfile
